<a href="https://colab.research.google.com/github/litlife8582/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

Creating a pandas list

In [14]:
my_series=[5,9,12,27]
my_var=pd.Series(my_series)
my_var

0     5
1     9
2    12
3    27
dtype: int64

In [15]:
my_var[2]

np.int64(12)

Putting index to out data values

In [16]:
my_index=["A","B","C","D"]
my_var2=pd.Series(my_series,my_index)
my_var2

A     5
B     9
C    12
D    27
dtype: int64

In [17]:
my_var2["B"]

np.int64(9)

Using python dictionary

In [18]:
cars={"Tesla":12,
      "Mercedes":42,
      "BMW":3}

my_var3=pd.Series(cars)
my_var3

Tesla       12
Mercedes    42
BMW          3
dtype: int64

Data Frames

Creating data frame makes it easier to visualize data

In [19]:
from numpy.random import random #creates random data

In [20]:
my_data=random((4,3))
my_rows=["A","B","C","D"]
my_columns=["Monday","Tuesday","Wednesday"]

In [21]:
my_df=pd.DataFrame(my_data,my_rows,my_columns)
my_df

     Monday   Tuesday  Wednesday
A  0.071175  0.698328   0.827321
B  0.411557  0.266423   0.217412
C  0.967807  0.786133   0.967703
D  0.810280  0.998970   0.890256

Importing csv file

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Importing csv file form google drive

In [23]:
file_path = '/content/drive/My Drive/Colab Notebooks/Pandas/DataSet.csv'
my_df2 = pd.read_csv(file_path)
print(my_df2.head())

   Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries
1  2023                     Level 1                99999       All industries
2  2023                     Level 1                99999       All industries
3  2023                     Level 1                99999       All industries
4  2023                     Level 1                99999       All industries

                Units Variable_code  \
0  Dollars (millions)           H01
1  Dollars (millions)           H04
2  Dollars (millions)           H05
3  Dollars (millions)           H07
4  Dollars (millions)           H08

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance
1  Sales, government funding, grants and subsidies  Financial performance
2                Interest, dividends and donations  Financial performance
3                             Non-operating income  Financial performance
4                                Total expenditure  Financial performance

    Value                             Industry_code_ANZSIC06
0  930995  ANZSIC06 divisions A-S (excluding classes K633...
1  821630  ANZSIC06 divisions A-S (excluding classes K633...
2   84354  ANZSIC06 divisions A-S (excluding classes K633...
3   25010  ANZSIC06 divisions A-S (excluding classes K633...
4  832964  ANZSIC06 divisions A-S (excluding classes K633...

Importing csv file from local system

In [24]:
from google.colab import files
uploaded = files.upload()

Saving DataSet.csv to DataSet.csv

In [25]:
my_df3=pd.read_csv('DataSet.csv')
my_df3

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

pulling out rows

In [26]:
my_df3.loc[0]

Year                                                                        2023
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     930995
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

pulling out multiple rows

In [27]:
my_df3.loc[[0,5]]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
5,2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...

Grabbing the first 'n' rows

data_frame_name.head(n)

In [28]:
my_df3.head(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
5,2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...
6,2023,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,7426,ANZSIC06 divisions A-S (excluding classes K633...
7,2023,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,30814,ANZSIC06 divisions A-S (excluding classes K633...
8,2023,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,147663,ANZSIC06 divisions A-S (excluding classes K633...
9,2023,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,269,ANZSIC06 divisions A-S (excluding classes K633...

Grabbing the last 'n' rows

data_frame_name.tail(n)

In [29]:
my_df3.tail(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
50975,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H32,Current liabilities,Financial position,"10,212","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50976,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H33,Other liabilities,Financial position,"2,220","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50977,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H34,Total income per employee count,Financial ratios,"523,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50978,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"17,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50979,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H36,Current ratio,Financial ratios,91,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

Leaving the parameters empty in the .head() and .tail() prints the first and the last 5 rows

data_frame_name.info() gives the information about the data frame

In [30]:
my_df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50985 entries, 0 to 50984
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         50985 non-null  int64
 1   Industry_aggregation_NZSIOC  50985 non-null  object
 2   Industry_code_NZSIOC         50985 non-null  object
 3   Industry_name_NZSIOC         50985 non-null  object
 4   Units                        50985 non-null  object
 5   Variable_code                50985 non-null  object
 6   Variable_name                50985 non-null  object
 7   Variable_category            50985 non-null  object
 8   Value                        50985 non-null  object
 9   Industry_code_ANZSIC06       50985 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.9+ MB

Shape of the data frame

In [31]:
my_df3.shape

(50985, 10)

Get infoo about the number of dimensions

In [32]:
my_df3.ndim

2