<a href="https://colab.research.google.com/github/litlife8582/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np

Creating a pandas list

In [12]:
my_series=[5,9,12,27]
my_var=pd.Series(my_series)
my_var

0     5
1     9
2    12
3    27
dtype: int64

In [13]:
my_var[2]

np.int64(12)

Putting index to out data values

In [14]:
my_index=["A","B","C","D"]
my_var2=pd.Series(my_series,my_index)
my_var2

A     5
B     9
C    12
D    27
dtype: int64

In [15]:
my_var2["B"]

np.int64(9)

Using python dictionary

In [16]:
cars={"Tesla":12,
      "Mercedes":42,
      "BMW":3}

my_var3=pd.Series(cars)
my_var3

Tesla       12
Mercedes    42
BMW          3
dtype: int64

Data Frames

Creating data frame makes it easier to visualize data

In [17]:
from numpy.random import random #creates random data

In [18]:
my_data=random((4,3))
my_rows=["A","B","C","D"]
my_columns=["Monday","Tuesday","Wednesday"]

In [19]:
my_df=pd.DataFrame(my_data,my_rows,my_columns)
my_df

     Monday   Tuesday  Wednesday
A  0.852919  0.614840   0.768932
B  0.555953  0.588932   0.658856
C  0.619440  0.495959   0.365749
D  0.768971  0.700338   0.370773

Importing csv file

Importing csv file form google drive

Importing csv file from local system

In [20]:
from google.colab import files
uploaded = files.upload()

Saving sim-companies-account-history-Orbia Corporations ltd..csv to sim-companies-account-history-Orbia Corporations ltd..csv

In [21]:
my_df3=pd.read_csv('sim-companies-account-history-Orbia Corporations ltd..csv')
my_df3

,id,Timestamp,Category,Money,Description,Details
0,2298740861,2025-04-29T09:42:18.261736+00:00,production,-1155,Production of Displays,"{""price"": ""$88.86"", ""quality"": 0, ""amount"": 100}"
1,2298740304,2025-04-29T09:41:39.466536+00:00,sales,10649,Sales of Laptops,"{""action"": ""take"", ""building"": {""id"": 42964461..."
2,2298740299,2025-04-29T09:41:38.907093+00:00,sales,11779,Sales of Televisions,"{""action"": ""take"", ""building"": {""id"": 43004130..."
3,2298740271,2025-04-29T09:41:37.686576+00:00,sales,10685,Sales of Laptops,"{""action"": ""take"", ""building"": {""id"": 43040062..."
4,2298302488,2025-04-29T00:08:59.481045+00:00,interest,-225,Bond interest payment,"{""bond value"": ""$45000"", ""interest"": ""0.5%"", ""..."
...,...,...,...,...,...,...
654,2260630673,2025-04-01T11:51:35.449936+00:00,sales,254,Sales of Apples,"{""action"": ""take"", ""building"": {""id"": 42693523..."
655,2260630205,2025-04-01T11:50:44.495016+00:00,production,-26,Production of Apples,"{""price"": ""$2.00"", ""quality"": 0, ""amount"": 50}"
656,2260629986,2025-04-01T11:50:06.698564+00:00,market,-15,Bought Seeds on market,"{""amount"": 50, ""price"": ""$0.30"", ""seller(s)"": ..."
657,2260629963,2025-04-01T11:49:58.979953+00:00,market,-59,Bought Water on market,"{""amount"": 150, ""price"": ""$0.39"", ""seller(s)"":..."
658,2260629274,2025-04-01T11:47:41.304730+00:00,game,500,Starting money,{}

pulling out rows

In [22]:
my_df3.loc[0]

id                                                   2298740861
Timestamp                      2025-04-29T09:42:18.261736+00:00
Category                                             production
Money                                                     -1155
Description                              Production of Displays
Details        {"price": "$88.86", "quality": 0, "amount": 100}
Name: 0, dtype: object

pulling out multiple rows

In [23]:
my_df3.loc[[0,5]]

,id,Timestamp,Category,Money,Description,Details
0,2298740861,2025-04-29T09:42:18.261736+00:00,production,-1155,Production of Displays,"{""price"": ""$88.86"", ""quality"": 0, ""amount"": 100}"
5,2298270246,2025-04-29T00:07:54.996072+00:00,interest,-425,Bond interest payment,"{""bond value"": ""$85000"", ""interest"": ""0.5%"", ""..."

Grabbing the first 'n' rows

data_frame_name.head(n)

In [24]:
my_df3.head(10)

,id,Timestamp,Category,Money,Description,Details
0,2298740861,2025-04-29T09:42:18.261736+00:00,production,-1155,Production of Displays,"{""price"": ""$88.86"", ""quality"": 0, ""amount"": 100}"
1,2298740304,2025-04-29T09:41:39.466536+00:00,sales,10649,Sales of Laptops,"{""action"": ""take"", ""building"": {""id"": 42964461..."
2,2298740299,2025-04-29T09:41:38.907093+00:00,sales,11779,Sales of Televisions,"{""action"": ""take"", ""building"": {""id"": 43004130..."
3,2298740271,2025-04-29T09:41:37.686576+00:00,sales,10685,Sales of Laptops,"{""action"": ""take"", ""building"": {""id"": 43040062..."
4,2298302488,2025-04-29T00:08:59.481045+00:00,interest,-225,Bond interest payment,"{""bond value"": ""$45000"", ""interest"": ""0.5%"", ""..."
5,2298270246,2025-04-29T00:07:54.996072+00:00,interest,-425,Bond interest payment,"{""bond value"": ""$85000"", ""interest"": ""0.5%"", ""..."
6,2298268580,2025-04-29T00:07:52.044084+00:00,interest,-425,Bond interest payment,"{""bond value"": ""$85000"", ""interest"": ""0.5%"", ""..."
7,2298264817,2025-04-29T00:07:45.491751+00:00,interest,-375,Bond interest payment,"{""bond value"": ""$75000"", ""interest"": ""0.5%"", ""..."
8,2298259869,2025-04-29T00:07:37.266021+00:00,interest,-160,Bond interest payment,"{""bond value"": ""$20000"", ""interest"": ""0.8%"", ""..."
9,2298253756,2025-04-29T00:07:27.285035+00:00,interest,-225,Bond interest payment,"{""bond value"": ""$45000"", ""interest"": ""0.5%"", ""..."

Grabbing the last 'n' rows

data_frame_name.tail(n)

In [25]:
my_df3.tail(10)

,id,Timestamp,Category,Money,Description,Details
649,2260633052,2025-04-01T11:58:10.435589+00:00,market,-154,Bought Seeds on market,"{""amount"": 500, ""price"": ""$0.31"", ""seller(s)"":..."
650,2260632427,2025-04-01T11:56:20.646383+00:00,market,-1750,Bought Software on market,"{""amount"": 10, ""price"": ""$175.00"", ""seller(s)""..."
651,2260632112,2025-04-01T11:55:21.008184+00:00,game,50,Achievement - Retailer,{}
652,2260632065,2025-04-01T11:55:13.755321+00:00,game,12000,Achievement - Tutorial Finished,{}
653,2260631858,2025-04-01T11:54:33.634259+00:00,market,-480,Bought Apples on market,"{""amount"": 150, ""price"": ""$3.20"", ""seller(s)"":..."
654,2260630673,2025-04-01T11:51:35.449936+00:00,sales,254,Sales of Apples,"{""action"": ""take"", ""building"": {""id"": 42693523..."
655,2260630205,2025-04-01T11:50:44.495016+00:00,production,-26,Production of Apples,"{""price"": ""$2.00"", ""quality"": 0, ""amount"": 50}"
656,2260629986,2025-04-01T11:50:06.698564+00:00,market,-15,Bought Seeds on market,"{""amount"": 50, ""price"": ""$0.30"", ""seller(s)"": ..."
657,2260629963,2025-04-01T11:49:58.979953+00:00,market,-59,Bought Water on market,"{""amount"": 150, ""price"": ""$0.39"", ""seller(s)"":..."
658,2260629274,2025-04-01T11:47:41.304730+00:00,game,500,Starting money,{}

Leaving the parameters empty in the .head() and .tail() prints the first and the last 5 rows

data_frame_name.info() gives the information about the data frame

In [26]:
my_df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659 entries, 0 to 658
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           659 non-null    int64
 1   Timestamp    659 non-null    object
 2   Category     659 non-null    object
 3   Money        659 non-null    int64
 4   Description  659 non-null    object
 5   Details      659 non-null    object
dtypes: int64(2), object(4)
memory usage: 31.0+ KB

Shape of the data frame

In [27]:
my_df3.shape

(659, 6)

Get info about the number of dimensions

In [28]:
my_df3.ndim

2

In [29]:
my_df3.dtypes

id              int64
Timestamp      object
Category       object
Money           int64
Description    object
Details        object
dtype: object

Statistical Data

In [30]:
my_df3.describe()

                 id         Money
count  6.590000e+02    659.000000
mean   2.282896e+09     58.726859
std    1.026374e+07  10058.923071
min    2.260629e+09 -58328.000000
25%    2.279349e+09  -1458.000000
50%    2.283253e+09   -154.000000
75%    2.289750e+09   1474.500000
max    2.298741e+09  85000.000000

In [31]:
my_df3['Money'].describe()

count      659.000000
mean        58.726859
std      10058.923071
min     -58328.000000
25%      -1458.000000
50%       -154.000000
75%       1474.500000
max      85000.000000
Name: Money, dtype: float64

In [32]:
my_df3['Description'].describe()

count                       659
unique                      116
top       Sales of Smart phones
freq                        121
Name: Description, dtype: object

In [33]:
my_df3['Description']

0      Production of Displays
1            Sales of Laptops
2        Sales of Televisions
3            Sales of Laptops
4       Bond interest payment
                ...
654           Sales of Apples
655      Production of Apples
656    Bought Seeds on market
657    Bought Water on market
658            Starting money
Name: Description, Length: 659, dtype: object

Syntax:

df_name.iloc[starting_index : ending_index, column_number]

In [34]:
my_df3.iloc[5:,5]

5      {"bond value": "$85000", "interest": "0.5%", "...
6      {"bond value": "$85000", "interest": "0.5%", "...
7      {"bond value": "$75000", "interest": "0.5%", "...
8      {"bond value": "$20000", "interest": "0.8%", "...
9      {"bond value": "$45000", "interest": "0.5%", "...
                             ...
654    {"action": "take", "building": {"id": 42693523...
655       {"price": "$2.00", "quality": 0, "amount": 50}
656    {"amount": 50, "price": "$0.30", "seller(s)": ...
657    {"amount": 150, "price": "$0.39", "seller(s)":...
658                                                   {}
Name: Details, Length: 654, dtype: object

Counts number of distinct kind of data

Syntax: df_name['Element'].value_count()

In [35]:
my_df3['Description'].value_counts()

Description
Sales of Smart phones              121
Bond interest payment               69
Sales of Laptops                    61
Sales of Underwear                  29
Bought Chemicals on market          28
                                  ...
Production of Coffee beans           1
Achievement - Tutorial Finished      1
Bought Apples on market              1
Production of Apples                 1
Starting money                       1
Name: count, Length: 116, dtype: int64

Finding the percentage(Normalizing)

Syntax:df_name['Element'].value_counts(normalize=True)

Percnetage value= Normalized value * 100

In [36]:
my_df3['Description'].value_counts(normalize=True)

Description
Sales of Smart phones              0.183612
Bond interest payment              0.104704
Sales of Laptops                   0.092564
Sales of Underwear                 0.044006
Bought Chemicals on market         0.042489
                                     ...
Production of Coffee beans         0.001517
Achievement - Tutorial Finished    0.001517
Bought Apples on market            0.001517
Production of Apples               0.001517
Starting money                     0.001517
Name: proportion, Length: 116, dtype: float64